# Site settings
title: "김여래 | Yeorae's Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "김여래"
resume_title:                   "DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kellyyeoraekim@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82 1076452966"
resume_contact_address:         ""

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>무엇보다도 문제를 해결하는 것이 중요하다고 생각합니다. 그리고 클라우드 기반의 DevOps 개발 문화는 해결 방법의 폭을 넓힐 수 있기 때문에 매력을 느꼈습니다. 따라서 DevOps 커리어를 위해서, AWS, Docker, Kubernetes, Node.js 등을 학습했고, 다른 사람들과 공유하는 경험을 쌓았습니다. <br /> 새로운 지식을 체화하기 위한 집중력과 끈기가 강점이며, 적재적소의 커뮤니케이션을 지향합니다. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_recognition:     true
resume_section_projects:        true
# resume_section_skills:          true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/yrkimyy"
  resume_twitter_url:           "http://twitter.com/devbellrae"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/여래-김-510509206"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://yrkimyy.github.io/"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
